### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by AcriCAA** [PhillyOpen/cyclephilly.org#4]
Instruction files need update with references to Cycle Philly instead of Cycle Atlanta.  

Nicole, can you handle this?  

https://github.com/PhillyOpen/cyclephilly.org/tree/master/cycleatlanta.org/instructions

**Comment by mchoimis** [comment]
Okay, I can definitely make edit on texts but let's see how we can change images appropriately (e.g., maps and logos).

**Comment by AcriCAA** [comment]
I'll work on those.

**Comment by mchoimis** [comment]
Just checked in, will work on this.

**Comment by AcriCAA** [comment]
Thanks. I can't make it tonight but I'll be back next week.

**Comment by mchoimis** [comment]
No problem, do I have to work under Instructions or instructions-v2?

**Comment by AcriCAA** [comment]
Sorry. Just saw this. Probably both.

**Comment by mchoimis** [comment]
Thanks, will do.

**Comment by mchoimis** [comment]
Done with the editing. Small issues: 
(1) logos (android)
(2) screenshots (iOS)
(3) license: previously, (c) 2013 Georgia State University

**Comment by AcriCAA** [comment]
I updated the screenshots in the instructions file. Thanks for doing the rest Nicole!
