### ISSUE TITLE
Rides not uploading where device ID length not 32

### ISSUE THREAD

**Issue by flibbertigibbet** [PhillyOpen/cyclephilly.org#6]
I found this check in post/index.php (which uploads trip data):

<pre>
// validate device ID
if ( is_string( $device ) && strlen( $device ) === 32 )
</pre>

I think if we were to remove the check for a 32-character device ID, that might fix both PhillyOpen/Cycle-Philly-Android#3 and #5.  (The device ID of the Android phone that won't upload trips is only 30 characters).

**Comment by AcriCAA** [comment]
This is still happening.  I cannot upload from my Android Kyocera Event.

**Comment by flibbertigibbet** [comment]
I removed the workaround in the test version.  The server code needs a
small fix.

Kathryn

**Comment by emelleme** [comment]
I've taken out the check for device id. Not sure if this will fix, but please let me know.

**Comment by AcriCAA** [comment]
It worked. That did  It. Thanks!
